// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EasyGenreMenuController from "./easy_genre_menu_controller"
application.register("easy-genre-menu", EasyGenreMenuController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PickyGenreMenuController from "./picky_genre_menu_controller"
application.register("picky-genre-menu", PickyGenreMenuController)
